version: "3"
services:
  ansible:
    image: lab_ubuntu_22_04_ansible:1.0
    volumes:
      - /home/ubuntu/ansible-conf:/etc/ansible
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
  ubuntu:
    image: lab_ubuntu_22_04:1.0
  lb:
    image: lab_ubuntu_22_04:1.0
    ports:
      - "80:80"
      - "443:443"
